COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:tinder-xmpp',
    '//protocols/xmpp/api:onos-protocols-xmpp-api',
    '//protocols/xmpp/ctl:onos-protocols-xmpp-ctl',
    '//apps/pubsub:onos-apps-pubsub',
]

TEST_DEPS = [
    '//lib:TEST',
    '//core/api:onos-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)